name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Standalone
        run: npm run build

      - name: Copy Standalone build
        run: cp -r dist dist-standalone

      - name: Zip Standalone assets
        run: zip -r standalone.zip dist-standalone

      - name: Build Library
        run: npx vite build --mode lib

      - name: Zip Library assets
        run: zip -r dist.zip dist

      - name: Set Release Tag
        id: set_tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=v$(node -p "JSON.parse(require('fs').readFileSync('package.json')).version")" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.zip,standalone.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist-standalone'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
